### PR TITLE
Airplane Plus Compatibility

### PR DESCRIPTION
**Pull request by Alioth81**
- added Airplane Plus compatibility Patch (ignore Airplane Plus rotors/prop meshes from voxelation and adds FAR configs for the aero parts) (should solve #16  )
- needed to add a small change so that the ignored mesh list is not overwritten
- added a fix to a division by 0 that theoretically could happen (related to my previous pull request #110 )

### CODE REVIEW

**Comment by Alioth81** [comment]
Small video showing a 5 part example helicopter and an airliner with some Airplane Plus parts
[https://www.youtube.com/watch?v=AXPjcaaZBB4](url)
some limitations:
- double fowler flaps are not possible with FAR as it only accepts one control surface module (therefore both surfaces are combined into a single flap)
- no other changes to the Airplane Plus parts (some wheels and the KT6C "Kitty" Turboshaft Engine seem glitchy but they are even without FAR, the power curves of the props seem a bit weird and overpowered. In addition many of the CoMs of the prop engines seem quite a bit off). However those changes are probably better done in the Airplane Plus mod itself.

**Review by tjradj — APPROVED** [review]

**Comment by dkavolis** [comment]
Thanks for the PR. Code changes look fine but the mod patch should be included with the mod itself rather than FAR.

**Comment by Alioth81** [comment]
I will open a pull request on Airplane Plus for the patch

**Comment by dkavolis** [comment]
Thanks

**Pull request merged**
