### PR TITLE
Use stock staging in RealChutes

### LINKED ISSUE #66: Space bar arms parachutes while stage lock on, even if something else has keyboard focus.
KSP 1.7.0 or KSP 1.7.1
FAR 0.15.10.1
ModularFlightIntegrator 1.2.6

Situation: while trying to run a kOS program while a plane is taking off, typing the space bar seems to deploy the drag chutes early. The drag chutes are the next stage. While typing into kOS stage lock is on and keyboard should not be affecting anything else.

After uninstalling everything, including kOS, having only FAR, module manager, and ModularFlightIntegrator installed, I noticed that if parachutes are in the next stage then space bar will arm them regardless of stage lock. This has obvious downsides when trying to take off from a runway.

### PR DESCRIPTION
**Pull request by dkavolis**
Fix #66

### CODE REVIEW

**Comment by evanrinehart** [comment]
Sorry for asking, but how should I test this chance given this pull request.

**Comment by dkavolis** [comment]
Replace DLLs in your GameData folder with the ones from this branch. Release are in GameData/Plugins, debug are in bin/Debug folrsers

**Comment by evanrinehart** [comment]
I just tested the modified DLL and it seems to fix the above problems. Staging parachutes still works as expected when you want it to.

**Comment by evanrinehart** [comment]
As far as I can tell this is ready, thanks a lot

**Pull request merged**
