### PR TITLE
Compatability to KSP1.8

### PR DESCRIPTION
**Pull request by lukecologne**
Quickly tested, GUI works, and it produces sensible values. Unfortunately I currently don't really have time for more extensive testing. Debug voxels don't work, probably need to update shaders.

### CODE REVIEW

**Comment by dkavolis** [comment]
Thanks for the PR, saved me some time setting up new Unity dependencies. I've updated shaders and version so if there are no problems this would be the release version. It seems that everything works fine in 1.8 but I would like to test some more. Binaries are included in the last commit.

**Comment by lukecologne** [comment]
Yes, that is probably best. I can take a quick look and search for any bugs, but I don't really have time for in-debth testing atm. unfortunately.

**Comment by lukecologne** [comment]
So, after a bit of testing, I didn't encounter any bugs at all. debug voxels work perfectly, sensible values when flying. I did not encounter NRE's when placing control surfaces, or loading crafts that were saved with FARControllableSurface, but I did get an NRE when loading stock crafts. They were the same as described [here](https://forum.kerbalspaceprogram.com/index.php?/topic/179445-14-17-ferram-aerospace-research-continued-v015112-mach-241019/&do=findComment&comment=3694749), so not created by FAR.

**Comment by dkavolis** [comment]
Thanks, it looks like the only issue is Scale_Redist, there are issues with loading it
```
ADDON BINDER: Cannot resolve assembly: Scale_Redist, Culture=neutral, PublicKeyToken=null
	UnityEngine.Debug:LogErrorFormat(String, Object[])
	AssemblyLoader:MyResolveEventHandler(Object, ResolveEventArgs)
	System.Reflection.Assembly:Load(AssemblyName)
	AssemblyLoader:MyResolveEventHandler(Object, ResolveEventArgs)
	System.Reflection.Assembly:GetTypes()
	AssemblyLoader:LoadAssemblies()
	<LoadObjects>d__89:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<CreateDatabase>d__70:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	GameDatabase:StartLoad()
	<LoadSystems>d__11:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	LoadingScreen:Start()
```
Tried recompiling with .NET 4.x and replacing Scale_Redist from currently maintained fork but I get the same errors everytime.

**Comment by dkavolis** [comment]
Ok, Scale_Redist is actually loaded so these `AssemblyLoader` errors are harmless.

**Pull request merged**
